source 'https://github.com/hanssea/IWSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'IWUserMainMoudle_Example' do
  pod 'IWUserMainMoudle', :path => '../'

  target 'IWUserMainMoudle_Tests' do
    inherit! :search_paths

    
  end
end
